-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mlp_core_stream is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    s_axis_feat_TDATA : IN STD_LOGIC_VECTOR (127 downto 0);
    s_axis_feat_TVALID : IN STD_LOGIC;
    s_axis_feat_TREADY : OUT STD_LOGIC;
    s_axis_feat_TKEEP : IN STD_LOGIC_VECTOR (15 downto 0);
    s_axis_feat_TSTRB : IN STD_LOGIC_VECTOR (15 downto 0);
    s_axis_feat_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axis_score_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axis_score_TVALID : OUT STD_LOGIC;
    m_axis_score_TREADY : IN STD_LOGIC;
    m_axis_score_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axis_score_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axis_score_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    done_pulse : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of mlp_core_stream is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "mlp_core_stream_mlp_core_stream,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.463000,HLS_SYN_LAT=1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=3,HLS_SYN_LUT=148,HLS_VERSION=2025_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";

    signal ap_rst_n_inv : STD_LOGIC;
    signal s_axis_feat_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal tmp_nbreadreq_fu_80_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal m_axis_score_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal tmp_reg_181 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal regslice_both_m_axis_score_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_block_state2 : BOOLEAN;
    signal tmp_2_fu_138_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_fu_134_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_3_fu_146_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_4_fu_154_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln47_1_fu_168_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln47_fu_162_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal regslice_both_s_axis_feat_V_data_V_U_apdone_blk : STD_LOGIC;
    signal s_axis_feat_TDATA_int_regslice : STD_LOGIC_VECTOR (127 downto 0);
    signal s_axis_feat_TVALID_int_regslice : STD_LOGIC;
    signal s_axis_feat_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_s_axis_feat_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_s_axis_feat_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal s_axis_feat_TKEEP_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal regslice_both_s_axis_feat_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_s_axis_feat_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_s_axis_feat_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal s_axis_feat_TSTRB_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal regslice_both_s_axis_feat_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_s_axis_feat_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_s_axis_feat_V_last_V_U_apdone_blk : STD_LOGIC;
    signal s_axis_feat_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_s_axis_feat_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_s_axis_feat_V_last_V_U_ack_in : STD_LOGIC;
    signal m_axis_score_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal m_axis_score_TVALID_int_regslice : STD_LOGIC;
    signal m_axis_score_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_m_axis_score_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_m_axis_score_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_m_axis_score_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_m_axis_score_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_m_axis_score_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_m_axis_score_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_m_axis_score_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_m_axis_score_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_m_axis_score_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_m_axis_score_V_last_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component mlp_core_stream_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    regslice_both_s_axis_feat_V_data_V_U : component mlp_core_stream_regslice_both
    generic map (
        DataWidth => 128)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => s_axis_feat_TDATA,
        vld_in => s_axis_feat_TVALID,
        ack_in => regslice_both_s_axis_feat_V_data_V_U_ack_in,
        data_out => s_axis_feat_TDATA_int_regslice,
        vld_out => s_axis_feat_TVALID_int_regslice,
        ack_out => s_axis_feat_TREADY_int_regslice,
        apdone_blk => regslice_both_s_axis_feat_V_data_V_U_apdone_blk);

    regslice_both_s_axis_feat_V_keep_V_U : component mlp_core_stream_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => s_axis_feat_TKEEP,
        vld_in => s_axis_feat_TVALID,
        ack_in => regslice_both_s_axis_feat_V_keep_V_U_ack_in,
        data_out => s_axis_feat_TKEEP_int_regslice,
        vld_out => regslice_both_s_axis_feat_V_keep_V_U_vld_out,
        ack_out => s_axis_feat_TREADY_int_regslice,
        apdone_blk => regslice_both_s_axis_feat_V_keep_V_U_apdone_blk);

    regslice_both_s_axis_feat_V_strb_V_U : component mlp_core_stream_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => s_axis_feat_TSTRB,
        vld_in => s_axis_feat_TVALID,
        ack_in => regslice_both_s_axis_feat_V_strb_V_U_ack_in,
        data_out => s_axis_feat_TSTRB_int_regslice,
        vld_out => regslice_both_s_axis_feat_V_strb_V_U_vld_out,
        ack_out => s_axis_feat_TREADY_int_regslice,
        apdone_blk => regslice_both_s_axis_feat_V_strb_V_U_apdone_blk);

    regslice_both_s_axis_feat_V_last_V_U : component mlp_core_stream_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => s_axis_feat_TLAST,
        vld_in => s_axis_feat_TVALID,
        ack_in => regslice_both_s_axis_feat_V_last_V_U_ack_in,
        data_out => s_axis_feat_TLAST_int_regslice,
        vld_out => regslice_both_s_axis_feat_V_last_V_U_vld_out,
        ack_out => s_axis_feat_TREADY_int_regslice,
        apdone_blk => regslice_both_s_axis_feat_V_last_V_U_apdone_blk);

    regslice_both_m_axis_score_V_data_V_U : component mlp_core_stream_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => m_axis_score_TDATA_int_regslice,
        vld_in => m_axis_score_TVALID_int_regslice,
        ack_in => m_axis_score_TREADY_int_regslice,
        data_out => m_axis_score_TDATA,
        vld_out => regslice_both_m_axis_score_V_data_V_U_vld_out,
        ack_out => m_axis_score_TREADY,
        apdone_blk => regslice_both_m_axis_score_V_data_V_U_apdone_blk);

    regslice_both_m_axis_score_V_keep_V_U : component mlp_core_stream_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv4_F,
        vld_in => m_axis_score_TVALID_int_regslice,
        ack_in => regslice_both_m_axis_score_V_keep_V_U_ack_in_dummy,
        data_out => m_axis_score_TKEEP,
        vld_out => regslice_both_m_axis_score_V_keep_V_U_vld_out,
        ack_out => m_axis_score_TREADY,
        apdone_blk => regslice_both_m_axis_score_V_keep_V_U_apdone_blk);

    regslice_both_m_axis_score_V_strb_V_U : component mlp_core_stream_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv4_F,
        vld_in => m_axis_score_TVALID_int_regslice,
        ack_in => regslice_both_m_axis_score_V_strb_V_U_ack_in_dummy,
        data_out => m_axis_score_TSTRB,
        vld_out => regslice_both_m_axis_score_V_strb_V_U_vld_out,
        ack_out => m_axis_score_TREADY,
        apdone_blk => regslice_both_m_axis_score_V_strb_V_U_apdone_blk);

    regslice_both_m_axis_score_V_last_V_U : component mlp_core_stream_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => s_axis_feat_TLAST_int_regslice,
        vld_in => m_axis_score_TVALID_int_regslice,
        ack_in => regslice_both_m_axis_score_V_last_V_U_ack_in_dummy,
        data_out => m_axis_score_TLAST,
        vld_out => regslice_both_m_axis_score_V_last_V_U_vld_out,
        ack_out => m_axis_score_TREADY,
        apdone_blk => regslice_both_m_axis_score_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                tmp_reg_181 <= tmp_nbreadreq_fu_80_p6;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_block_state1, ap_block_state2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_boolean_0 = ap_block_state2) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    acc_fu_134_p1 <= s_axis_feat_TDATA_int_regslice(32 - 1 downto 0);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(ap_block_state2)
    begin
        if ((ap_const_boolean_1 = ap_block_state2)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(tmp_nbreadreq_fu_80_p6, s_axis_feat_TVALID_int_regslice, m_axis_score_TREADY_int_regslice)
    begin
                ap_block_state1 <= (((tmp_nbreadreq_fu_80_p6 = ap_const_lv1_1) and (m_axis_score_TREADY_int_regslice = ap_const_logic_0)) or ((tmp_nbreadreq_fu_80_p6 = ap_const_lv1_1) and (s_axis_feat_TVALID_int_regslice = ap_const_logic_0)));
    end process;


    ap_block_state2_assign_proc : process(tmp_reg_181, regslice_both_m_axis_score_V_data_V_U_apdone_blk, m_axis_score_TREADY_int_regslice)
    begin
                ap_block_state2 <= ((regslice_both_m_axis_score_V_data_V_U_apdone_blk = ap_const_logic_1) or ((tmp_reg_181 = ap_const_lv1_1) and (m_axis_score_TREADY_int_regslice = ap_const_logic_0)));
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    done_pulse_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, tmp_reg_181, ap_block_state1, ap_block_state2)
    begin
        if (((ap_const_boolean_0 = ap_block_state2) and (tmp_reg_181 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            done_pulse <= ap_const_lv1_1;
        elsif (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            done_pulse <= ap_const_lv1_0;
        else 
            done_pulse <= "X";
        end if; 
    end process;


    m_axis_score_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state1, tmp_nbreadreq_fu_80_p6, ap_CS_fsm_state2, tmp_reg_181, m_axis_score_TREADY_int_regslice)
    begin
        if ((((tmp_reg_181 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((tmp_nbreadreq_fu_80_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            m_axis_score_TDATA_blk_n <= m_axis_score_TREADY_int_regslice;
        else 
            m_axis_score_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    m_axis_score_TDATA_int_regslice <= (xor_ln47_fu_162_p2 xor xor_ln47_1_fu_168_p2);
    m_axis_score_TVALID <= regslice_both_m_axis_score_V_data_V_U_vld_out;

    m_axis_score_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_state1, tmp_nbreadreq_fu_80_p6, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (tmp_nbreadreq_fu_80_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            m_axis_score_TVALID_int_regslice <= ap_const_logic_1;
        else 
            m_axis_score_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    s_axis_feat_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state1, tmp_nbreadreq_fu_80_p6, s_axis_feat_TVALID_int_regslice)
    begin
        if (((tmp_nbreadreq_fu_80_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            s_axis_feat_TDATA_blk_n <= s_axis_feat_TVALID_int_regslice;
        else 
            s_axis_feat_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    s_axis_feat_TREADY <= regslice_both_s_axis_feat_V_data_V_U_ack_in;

    s_axis_feat_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_state1, tmp_nbreadreq_fu_80_p6, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (tmp_nbreadreq_fu_80_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            s_axis_feat_TREADY_int_regslice <= ap_const_logic_1;
        else 
            s_axis_feat_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    tmp_2_fu_138_p3 <= s_axis_feat_TDATA_int_regslice(63 downto 32);
    tmp_3_fu_146_p3 <= s_axis_feat_TDATA_int_regslice(95 downto 64);
    tmp_4_fu_154_p3 <= s_axis_feat_TDATA_int_regslice(127 downto 96);
    tmp_nbreadreq_fu_80_p6 <= (0=>(s_axis_feat_TVALID_int_regslice), others=>'-');
    xor_ln47_1_fu_168_p2 <= (tmp_4_fu_154_p3 xor tmp_3_fu_146_p3);
    xor_ln47_fu_162_p2 <= (tmp_2_fu_138_p3 xor acc_fu_134_p1);
end behav;
