// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="score_sink_score_sink,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=1.808000,HLS_SYN_LAT=1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=4,HLS_SYN_LUT=41,HLS_VERSION=2025_1}" *)

module score_sink (
        ap_clk,
        ap_rst_n,
        s_axis_score_TDATA,
        s_axis_score_TVALID,
        s_axis_score_TREADY,
        s_axis_score_TKEEP,
        s_axis_score_TSTRB,
        s_axis_score_TLAST,
        done_pulse
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst_n;
input  [31:0] s_axis_score_TDATA;
input   s_axis_score_TVALID;
output   s_axis_score_TREADY;
input  [3:0] s_axis_score_TKEEP;
input  [3:0] s_axis_score_TSTRB;
input  [0:0] s_axis_score_TLAST;
output  [0:0] done_pulse;

reg[0:0] done_pulse;

 reg    ap_rst_n_inv;
reg    s_axis_score_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] tmp_nbreadreq_fu_58_p6;
reg   [0:0] tmp_reg_89;
reg   [0:0] w_last_reg_93;
reg    ap_block_state1;
wire    ap_CS_fsm_state2;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    regslice_both_s_axis_score_V_data_V_U_apdone_blk;
wire   [31:0] s_axis_score_TDATA_int_regslice;
wire    s_axis_score_TVALID_int_regslice;
reg    s_axis_score_TREADY_int_regslice;
wire    regslice_both_s_axis_score_V_data_V_U_ack_in;
wire    regslice_both_s_axis_score_V_keep_V_U_apdone_blk;
wire   [3:0] s_axis_score_TKEEP_int_regslice;
wire    regslice_both_s_axis_score_V_keep_V_U_vld_out;
wire    regslice_both_s_axis_score_V_keep_V_U_ack_in;
wire    regslice_both_s_axis_score_V_strb_V_U_apdone_blk;
wire   [3:0] s_axis_score_TSTRB_int_regslice;
wire    regslice_both_s_axis_score_V_strb_V_U_vld_out;
wire    regslice_both_s_axis_score_V_strb_V_U_ack_in;
wire    regslice_both_s_axis_score_V_last_V_U_apdone_blk;
wire   [0:0] s_axis_score_TLAST_int_regslice;
wire    regslice_both_s_axis_score_V_last_V_U_vld_out;
wire    regslice_both_s_axis_score_V_last_V_U_ack_in;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
end

score_sink_regslice_both #(
    .DataWidth( 32 ))
regslice_both_s_axis_score_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_score_TDATA),
    .vld_in(s_axis_score_TVALID),
    .ack_in(regslice_both_s_axis_score_V_data_V_U_ack_in),
    .data_out(s_axis_score_TDATA_int_regslice),
    .vld_out(s_axis_score_TVALID_int_regslice),
    .ack_out(s_axis_score_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_score_V_data_V_U_apdone_blk)
);

score_sink_regslice_both #(
    .DataWidth( 4 ))
regslice_both_s_axis_score_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_score_TKEEP),
    .vld_in(s_axis_score_TVALID),
    .ack_in(regslice_both_s_axis_score_V_keep_V_U_ack_in),
    .data_out(s_axis_score_TKEEP_int_regslice),
    .vld_out(regslice_both_s_axis_score_V_keep_V_U_vld_out),
    .ack_out(s_axis_score_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_score_V_keep_V_U_apdone_blk)
);

score_sink_regslice_both #(
    .DataWidth( 4 ))
regslice_both_s_axis_score_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_score_TSTRB),
    .vld_in(s_axis_score_TVALID),
    .ack_in(regslice_both_s_axis_score_V_strb_V_U_ack_in),
    .data_out(s_axis_score_TSTRB_int_regslice),
    .vld_out(regslice_both_s_axis_score_V_strb_V_U_vld_out),
    .ack_out(s_axis_score_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_score_V_strb_V_U_apdone_blk)
);

score_sink_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_score_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_score_TLAST),
    .vld_in(s_axis_score_TVALID),
    .ack_in(regslice_both_s_axis_score_V_last_V_U_ack_in),
    .data_out(s_axis_score_TLAST_int_regslice),
    .vld_out(regslice_both_s_axis_score_V_last_V_U_vld_out),
    .ack_out(s_axis_score_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_score_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        tmp_reg_89 <= tmp_nbreadreq_fu_58_p6;
        w_last_reg_93 <= s_axis_score_TLAST_int_regslice;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if (((w_last_reg_93 == 1'd1) & (tmp_reg_89 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        done_pulse = 1'd1;
    end else if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        done_pulse = 1'd0;
    end else begin
        done_pulse = 'bx;
    end
end

always @ (*) begin
    if (((tmp_nbreadreq_fu_58_p6 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        s_axis_score_TDATA_blk_n = s_axis_score_TVALID_int_regslice;
    end else begin
        s_axis_score_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (tmp_nbreadreq_fu_58_p6 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        s_axis_score_TREADY_int_regslice = 1'b1;
    end else begin
        s_axis_score_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((s_axis_score_TVALID_int_regslice == 1'b0) & (tmp_nbreadreq_fu_58_p6 == 1'd1));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign s_axis_score_TREADY = regslice_both_s_axis_score_V_data_V_U_ack_in;

assign tmp_nbreadreq_fu_58_p6 = s_axis_score_TVALID_int_regslice;


reg find_kernel_block = 0;
// synthesis translate_off
`include "score_sink_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //score_sink

