// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="mlp_core_stream_mlp_core_stream,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.463000,HLS_SYN_LAT=1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=3,HLS_SYN_LUT=148,HLS_VERSION=2025_1}" *)

module mlp_core_stream (
        ap_clk,
        ap_rst_n,
        s_axis_feat_TDATA,
        s_axis_feat_TVALID,
        s_axis_feat_TREADY,
        s_axis_feat_TKEEP,
        s_axis_feat_TSTRB,
        s_axis_feat_TLAST,
        m_axis_score_TDATA,
        m_axis_score_TVALID,
        m_axis_score_TREADY,
        m_axis_score_TKEEP,
        m_axis_score_TSTRB,
        m_axis_score_TLAST,
        done_pulse
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst_n;
input  [127:0] s_axis_feat_TDATA;
input   s_axis_feat_TVALID;
output   s_axis_feat_TREADY;
input  [15:0] s_axis_feat_TKEEP;
input  [15:0] s_axis_feat_TSTRB;
input  [0:0] s_axis_feat_TLAST;
output  [31:0] m_axis_score_TDATA;
output   m_axis_score_TVALID;
input   m_axis_score_TREADY;
output  [3:0] m_axis_score_TKEEP;
output  [3:0] m_axis_score_TSTRB;
output  [0:0] m_axis_score_TLAST;
output  [0:0] done_pulse;

reg[0:0] done_pulse;

 reg    ap_rst_n_inv;
reg    s_axis_feat_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] tmp_nbreadreq_fu_80_p6;
reg    m_axis_score_TDATA_blk_n;
wire    ap_CS_fsm_state2;
reg   [0:0] tmp_reg_181;
reg    ap_block_state1;
wire    regslice_both_m_axis_score_V_data_V_U_apdone_blk;
reg    ap_block_state2;
wire   [31:0] tmp_2_fu_138_p3;
wire   [31:0] acc_fu_134_p1;
wire   [31:0] tmp_3_fu_146_p3;
wire   [31:0] tmp_4_fu_154_p3;
wire   [31:0] xor_ln47_1_fu_168_p2;
wire   [31:0] xor_ln47_fu_162_p2;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    regslice_both_s_axis_feat_V_data_V_U_apdone_blk;
wire   [127:0] s_axis_feat_TDATA_int_regslice;
wire    s_axis_feat_TVALID_int_regslice;
reg    s_axis_feat_TREADY_int_regslice;
wire    regslice_both_s_axis_feat_V_data_V_U_ack_in;
wire    regslice_both_s_axis_feat_V_keep_V_U_apdone_blk;
wire   [15:0] s_axis_feat_TKEEP_int_regslice;
wire    regslice_both_s_axis_feat_V_keep_V_U_vld_out;
wire    regslice_both_s_axis_feat_V_keep_V_U_ack_in;
wire    regslice_both_s_axis_feat_V_strb_V_U_apdone_blk;
wire   [15:0] s_axis_feat_TSTRB_int_regslice;
wire    regslice_both_s_axis_feat_V_strb_V_U_vld_out;
wire    regslice_both_s_axis_feat_V_strb_V_U_ack_in;
wire    regslice_both_s_axis_feat_V_last_V_U_apdone_blk;
wire   [0:0] s_axis_feat_TLAST_int_regslice;
wire    regslice_both_s_axis_feat_V_last_V_U_vld_out;
wire    regslice_both_s_axis_feat_V_last_V_U_ack_in;
wire   [31:0] m_axis_score_TDATA_int_regslice;
reg    m_axis_score_TVALID_int_regslice;
wire    m_axis_score_TREADY_int_regslice;
wire    regslice_both_m_axis_score_V_data_V_U_vld_out;
wire    regslice_both_m_axis_score_V_keep_V_U_apdone_blk;
wire    regslice_both_m_axis_score_V_keep_V_U_ack_in_dummy;
wire    regslice_both_m_axis_score_V_keep_V_U_vld_out;
wire    regslice_both_m_axis_score_V_strb_V_U_apdone_blk;
wire    regslice_both_m_axis_score_V_strb_V_U_ack_in_dummy;
wire    regslice_both_m_axis_score_V_strb_V_U_vld_out;
wire    regslice_both_m_axis_score_V_last_V_U_apdone_blk;
wire    regslice_both_m_axis_score_V_last_V_U_ack_in_dummy;
wire    regslice_both_m_axis_score_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
end

mlp_core_stream_regslice_both #(
    .DataWidth( 128 ))
regslice_both_s_axis_feat_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_feat_TDATA),
    .vld_in(s_axis_feat_TVALID),
    .ack_in(regslice_both_s_axis_feat_V_data_V_U_ack_in),
    .data_out(s_axis_feat_TDATA_int_regslice),
    .vld_out(s_axis_feat_TVALID_int_regslice),
    .ack_out(s_axis_feat_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_feat_V_data_V_U_apdone_blk)
);

mlp_core_stream_regslice_both #(
    .DataWidth( 16 ))
regslice_both_s_axis_feat_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_feat_TKEEP),
    .vld_in(s_axis_feat_TVALID),
    .ack_in(regslice_both_s_axis_feat_V_keep_V_U_ack_in),
    .data_out(s_axis_feat_TKEEP_int_regslice),
    .vld_out(regslice_both_s_axis_feat_V_keep_V_U_vld_out),
    .ack_out(s_axis_feat_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_feat_V_keep_V_U_apdone_blk)
);

mlp_core_stream_regslice_both #(
    .DataWidth( 16 ))
regslice_both_s_axis_feat_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_feat_TSTRB),
    .vld_in(s_axis_feat_TVALID),
    .ack_in(regslice_both_s_axis_feat_V_strb_V_U_ack_in),
    .data_out(s_axis_feat_TSTRB_int_regslice),
    .vld_out(regslice_both_s_axis_feat_V_strb_V_U_vld_out),
    .ack_out(s_axis_feat_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_feat_V_strb_V_U_apdone_blk)
);

mlp_core_stream_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_feat_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_feat_TLAST),
    .vld_in(s_axis_feat_TVALID),
    .ack_in(regslice_both_s_axis_feat_V_last_V_U_ack_in),
    .data_out(s_axis_feat_TLAST_int_regslice),
    .vld_out(regslice_both_s_axis_feat_V_last_V_U_vld_out),
    .ack_out(s_axis_feat_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_feat_V_last_V_U_apdone_blk)
);

mlp_core_stream_regslice_both #(
    .DataWidth( 32 ))
regslice_both_m_axis_score_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(m_axis_score_TDATA_int_regslice),
    .vld_in(m_axis_score_TVALID_int_regslice),
    .ack_in(m_axis_score_TREADY_int_regslice),
    .data_out(m_axis_score_TDATA),
    .vld_out(regslice_both_m_axis_score_V_data_V_U_vld_out),
    .ack_out(m_axis_score_TREADY),
    .apdone_blk(regslice_both_m_axis_score_V_data_V_U_apdone_blk)
);

mlp_core_stream_regslice_both #(
    .DataWidth( 4 ))
regslice_both_m_axis_score_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd15),
    .vld_in(m_axis_score_TVALID_int_regslice),
    .ack_in(regslice_both_m_axis_score_V_keep_V_U_ack_in_dummy),
    .data_out(m_axis_score_TKEEP),
    .vld_out(regslice_both_m_axis_score_V_keep_V_U_vld_out),
    .ack_out(m_axis_score_TREADY),
    .apdone_blk(regslice_both_m_axis_score_V_keep_V_U_apdone_blk)
);

mlp_core_stream_regslice_both #(
    .DataWidth( 4 ))
regslice_both_m_axis_score_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd15),
    .vld_in(m_axis_score_TVALID_int_regslice),
    .ack_in(regslice_both_m_axis_score_V_strb_V_U_ack_in_dummy),
    .data_out(m_axis_score_TSTRB),
    .vld_out(regslice_both_m_axis_score_V_strb_V_U_vld_out),
    .ack_out(m_axis_score_TREADY),
    .apdone_blk(regslice_both_m_axis_score_V_strb_V_U_apdone_blk)
);

mlp_core_stream_regslice_both #(
    .DataWidth( 1 ))
regslice_both_m_axis_score_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_feat_TLAST_int_regslice),
    .vld_in(m_axis_score_TVALID_int_regslice),
    .ack_in(regslice_both_m_axis_score_V_last_V_U_ack_in_dummy),
    .data_out(m_axis_score_TLAST),
    .vld_out(regslice_both_m_axis_score_V_last_V_U_vld_out),
    .ack_out(m_axis_score_TREADY),
    .apdone_blk(regslice_both_m_axis_score_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        tmp_reg_181 <= tmp_nbreadreq_fu_80_p6;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2) & (tmp_reg_181 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        done_pulse = 1'd1;
    end else if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        done_pulse = 1'd0;
    end else begin
        done_pulse = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_reg_181 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((tmp_nbreadreq_fu_80_p6 == 1'd1) & (1'b1 == ap_CS_fsm_state1)))) begin
        m_axis_score_TDATA_blk_n = m_axis_score_TREADY_int_regslice;
    end else begin
        m_axis_score_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (tmp_nbreadreq_fu_80_p6 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        m_axis_score_TVALID_int_regslice = 1'b1;
    end else begin
        m_axis_score_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_nbreadreq_fu_80_p6 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        s_axis_feat_TDATA_blk_n = s_axis_feat_TVALID_int_regslice;
    end else begin
        s_axis_feat_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (tmp_nbreadreq_fu_80_p6 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        s_axis_feat_TREADY_int_regslice = 1'b1;
    end else begin
        s_axis_feat_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_fu_134_p1 = s_axis_feat_TDATA_int_regslice[31:0];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = (((tmp_nbreadreq_fu_80_p6 == 1'd1) & (m_axis_score_TREADY_int_regslice == 1'b0)) | ((tmp_nbreadreq_fu_80_p6 == 1'd1) & (s_axis_feat_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_state2 = ((regslice_both_m_axis_score_V_data_V_U_apdone_blk == 1'b1) | ((tmp_reg_181 == 1'd1) & (m_axis_score_TREADY_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign m_axis_score_TDATA_int_regslice = (xor_ln47_fu_162_p2 ^ xor_ln47_1_fu_168_p2);

assign m_axis_score_TVALID = regslice_both_m_axis_score_V_data_V_U_vld_out;

assign s_axis_feat_TREADY = regslice_both_s_axis_feat_V_data_V_U_ack_in;

assign tmp_2_fu_138_p3 = {{s_axis_feat_TDATA_int_regslice[63:32]}};

assign tmp_3_fu_146_p3 = {{s_axis_feat_TDATA_int_regslice[95:64]}};

assign tmp_4_fu_154_p3 = {{s_axis_feat_TDATA_int_regslice[127:96]}};

assign tmp_nbreadreq_fu_80_p6 = s_axis_feat_TVALID_int_regslice;

assign xor_ln47_1_fu_168_p2 = (tmp_4_fu_154_p3 ^ tmp_3_fu_146_p3);

assign xor_ln47_fu_162_p2 = (tmp_2_fu_138_p3 ^ acc_fu_134_p1);

endmodule //mlp_core_stream
